// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwxyzB2A5sg7-ruH49HQT8J5NUOxWIYc8',
    appId: '1:405132171539:web:b4f6dd91d13712339222e6',
    messagingSenderId: '405132171539',
    projectId: 'my-project-bbffa',
    authDomain: 'my-project-bbffa.firebaseapp.com',
    storageBucket: 'my-project-bbffa.appspot.com',
    measurementId: 'G-5V3KK31EC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqvDi95AE5quVvK6rinCL1-1UuxaZnAo',
    appId: '1:405132171539:android:65ffb7c3aa00c5a69222e6',
    messagingSenderId: '405132171539',
    projectId: 'my-project-bbffa',
    storageBucket: 'my-project-bbffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PTH63G239TMh77SjWs97KST3-MQNvz4',
    appId: '1:405132171539:ios:ed0f00de1633688b9222e6',
    messagingSenderId: '405132171539',
    projectId: 'my-project-bbffa',
    storageBucket: 'my-project-bbffa.appspot.com',
    iosClientId: '405132171539-uko11dibrsqvgtvqnvlv9qj5e9d23t1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.marapay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PTH63G239TMh77SjWs97KST3-MQNvz4',
    appId: '1:405132171539:ios:ed0f00de1633688b9222e6',
    messagingSenderId: '405132171539',
    projectId: 'my-project-bbffa',
    storageBucket: 'my-project-bbffa.appspot.com',
    iosClientId: '405132171539-uko11dibrsqvgtvqnvlv9qj5e9d23t1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.marapay',
  );
}
